Lab2/ViewModels/ThreadViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Lab2.Models.Entities;

namespace Lab2.ViewModels
{
    public class ThreadViewModel
    {
        public ForumThread ForumThread { get; set; }
        public List<Post> Posts { get; set; }
    }
}

Lab2/Controllers/ForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2.Models.Entities;
using Lab2.Models.Repositories;
using Lab2.ViewModels;
using Lab2.Models.SessionManager;

namespace Lab2.Controllers
{
    public class ForumsController : Controller
    {
        //
        // GET: /Forums/

        public ActionResult Index()
        {
            List<ForumThread> Threads = Repository.Instance.GetSortedThreads();

            return View(Threads);
        }

        public ActionResult Thread(Guid id)
        {
            ThreadViewModel vm = new ThreadViewModel();
            vm.ForumThread = Repository.Instance.Get<ForumThread>(id);
            vm.Posts = Repository.Instance.GetPostsByThreadID(id);
            return View(vm);
        }

        public ActionResult CreatePost()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreatePost(Guid id, Post post)
        {
            return View();
        }



    }
}

Lab2/Views/Forums/CreatePost.cshtml
@{
    ViewBag.Title = "CreatePost";
}

<h2>CreatePost</h2>

Lab2/Views/Forums/Index.cshtml
@using Lab2.Models.Entities;
@model List<ForumThread>
@{
    ViewBag.Title = "Index";
}


           
<h2>Forums</h2>
<p>
    @Html.ActionLink("Create post", "CreatePost", "Forums")
</p>
<table>
@foreach (var Thread in Model)
{
    <tr>
        <td>@Thread.ID</td>
        <td>@Html.ActionLink(Thread.Title, "Thread", "Forums", new { id = Thread.ID }, null)</td>
        <td>@Thread.CreateDate</td>
    </tr>
}
</table>

Lab2/Views/Forums/Thread.cshtml
@using Lab2.ViewModels
@model ThreadViewModel
@{
    ViewBag.Title = "Thread";
}

<h2>Thread: @Html.DisplayFor(p => p.ForumThread.Title)</h2>

<p>
    @Html.ActionLink("Create post", "CreatePost", "Forums")
</p>

<div class="capclear2 aw detailspanel">

    @foreach (var item in Model.Posts)
    {
        <ul>
            <li>
                <span>@Html.LabelFor(i => item.CreateDate):</span>@Html.DisplayFor(i => item.CreateDate)
            </li>
            <li>
                <span>@Html.LabelFor(i => item.Title):</span>@Html.DisplayFor(i => item.Title)
            </li>
            <li>
                <span>@Html.LabelFor(i => item.Body):</span>@Html.DisplayFor(i => item.Body)
            </li>
        </ul>
    }
 </div>